spring.application.name=crudapp

frontend-url=${REACT_URL}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

ml.service.base-url=${ML_API_URL}
ml.service.train=${ML_API_TRAIN_ENDPOINT}
ml.service.predict=${ML_API_PREDICT_ENDPOINT}

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.mvc.async.request-timeout=60000